#lang racket
(provide (all-defined-out))

(struct app (e0 e1)    #:prefab)
(struct lam (x  e)     #:prefab)
(struct vbl (x)        #:prefab)
(struct num (n)        #:prefab)
(struct ifz (e0 e1 e2) #:prefab)
(struct op1 (o e)      #:prefab)
(struct op2 (o e0 e1)  #:prefab)
(struct ref (e)        #:prefab)
(struct drf (e)        #:prefab)
(struct srf (e0 e1)    #:prefab)
(struct sym (s)        #:prefab)
(struct lrc (f x e)    #:prefab)